pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "sandu418/SeekerService"      // change to your Docker Hub username & service name
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/SanduniS/SkillBridgeLankaapplication.git'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn -f SeekerService/pom.xml clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} SeekerService/"
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'sandu418', passwordVariable: 'Sanduni@25241')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"
            }
        }
    }
}
