pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "sandu418/applicationservice"      // change to your Docker Hub username & service name
        DOCKER_TAG = "latest"
        DB_URL       = "jdbc:mysql://host.docker.internal:3306/ApplicationService"
        DB_USER      = "root"
        DB_PASS      = ""
        CONTAINER_NAME = "applicationservice-container"
        APP_PORT     = "8088"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/SanduniS/SkillBridgeLankaapplication.git'
            }
        }

        stage('Build with Maven') {
            steps {
                bat 'mvn -f ApplicationService/pom.xml clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    bat "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ApplicationService/"
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    bat 'echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                bat "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"
            }
        }
        stage('Run Docker Container') {
                    steps {
                        bat """
                        docker rm -f ${env.CONTAINER_NAME} || echo Container does not exist
                        docker run -d ^
                            --name ${env.CONTAINER_NAME} ^
                            -e DB_URL=${env.DB_URL} ^
                            -e DB_USER=${env.DB_USER} ^
                            -e DB_PASS=${env.DB_PASS} ^
                            -p ${env.APP_PORT}:${env.APP_PORT} ^
                            ${env.DOCKER_IMAGE}:${env.DOCKER_TAG}
                        """
                    }
                }
    }
}
