pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "sandu418/jobservice"      // change to your Docker Hub username & service name
        DOCKER_TAG = "latest"
        DB_URL = "jdbc:mysql://host.docker.internal:3306/JobService"
        DB_USER      = "root"
        DB_PASS      = ""
        CONTAINER_NAME = "jobservice-container"
        APP_PORT     = "8083"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/SanduniS/SkillBridgeLankaapplication.git'
            }
        }

        stage('Build with Maven') {
            steps {
                bat 'mvn -f Job-Service/pom.xml clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    bat "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} Job-Service/"
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    bat 'echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                bat "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"
            }
        }
    }
}
